import { profile } from "../images/images";

export const HealthDetails = [
    {
        "id": "1",
        "userId": "1",
        "name": "Charvie Sharma",
        "email": "Charviesharma@gmail.com",
        "stepsWalked": "2547",
        "stepsTarget": "4000",
        "performedDate": "15 Oct",
        "scheduledDate": "22 Oct",
        "calorieIntake": "2547",
        "calorieTarget": "2500",
        "proteinConsumed": "2547",
        "proteinTarget": "3000",
        "carbConsumed": "2547",
        "carbTarget": "3500",
        "fatConsumed": "2547",
        "fatTarget": "2000",
        "img": profile,
        "feedback": "true",
        "showToolTip": false,
    },
    {
        "id": "2",
        "userId": "2",
        "name": "Charvie Sharma",
        "email": "Charviesharma@gmail.com",
        "stepsWalked": "2547",
        "stepsTarget": "4000",
        "performedDate": "15 Oct",
        "scheduledDate": "22 Oct",
        "calorieIntake": "2547",
        "calorieTarget": "2500",
        "proteinConsumed": "2547",
        "proteinTarget": "3000",
        "carbConsumed": "2547",
        "carbTarget": "3500",
        "fatConsumed": "2547",
        "fatTarget": "2000",
        "img": profile,
        "feedback": "true",
        "showToolTip": false,
    },
    {
        "id": "3",
        "userId": "3",
        "name": "Charvie Sharma",
        "email": "Charviesharma@gmail.com",
        "stepsWalked": "2547",
        "stepsTarget": "4000",
        "performedDate": "15 Oct",
        "scheduledDate": "22 Oct",
        "calorieIntake": "2547",
        "calorieTarget": "2500",
        "proteinConsumed": "2547",
        "proteinTarget": "3000",
        "carbConsumed": "2547",
        "carbTarget": "3500",
        "fatConsumed": "2547",
        "fatTarget": "2000",
        "img": profile,
        "feedback": "false",
        "showToolTip": false,
    }
]